import {
  Home,
  Car,
  Utensils,
  Film,
  HeartPulse,
  ShoppingBag,
  Lightbulb,
  Briefcase,
  PencilRuler,
  AreaChart,
  Landmark,
  MoreHorizontal,
  LayoutDashboard,
  ArrowRightLeft,
  FileText,
  Bot,
  User,
  LogOut,
  Wallet,
} from 'lucide-react';

export const Icons = {
  home: Home,
  car: Car,
  utensils: Utensils,
  film: Film,
  heartPulse: HeartPulse,
  shoppingBag: ShoppingBag,
  lightbulb: Lightbulb,
  briefcase: Briefcase,
  pencilRuler: PencilRuler,
  areaChart: AreaChart,
  landmark: Landmark,
  more: MoreHorizontal,
  dashboard: LayoutDashboard,
  transactions: ArrowRightLeft,
  reports: FileText,
  budgetAI: Bot,
  user: User,
  logout: LogOut,
  wallet: Wallet,
};
